"""cree tabla areas y empleados 

Revision ID: 23fa48eb4e05
Revises: 8edbc2ac47f6
Create Date: 2023-05-27 16:45:07.644663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fa48eb4e05'
down_revision = '8edbc2ac47f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('Areas', 'areas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('areas', 'Areas')

    # ### end Alembic commands ###
